package dc

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
)

// RecipientsFile is the backup recipients list the operator mounts
// (compose configs:); the init copies it root-owned 0600 to tmpfs because
// conductor-helper refuses a recipients file anyone else can write.
const RecipientsFile = "/etc/sc/backup-recipients.txt"

// writeHelperConfig generates conductor-helper's configuration at every
// start into tmpfs (no state, nothing to drift): backups off, or the
// [backup] section with the account password and recipients copied to
// root-only files.
func (r *Runner) writeHelperConfig() error {
	c := r.Cfg
	p := filepath.Join(RunDir, "helper.toml")
	if !c.Backup {
		return writeFileAtomic(p, []byte("# Generated by sc-dc-init at every start (SC_BACKUP=off).\n[backup]\nenabled = false\n"), 0o600)
	}
	pw, err := os.ReadFile(filepath.Join(SecretsDir, "backup-account"))
	if err != nil {
		return fmt.Errorf("SC_BACKUP=on needs the backup-account secret (the password of %s): %w", c.BackupAccount, err)
	}
	if err := writeFileAtomic(filepath.Join(RunDir, "backup-account"), pw, 0o600); err != nil {
		return err
	}
	rec, err := os.ReadFile(RecipientsFile)
	if err != nil {
		return fmt.Errorf("SC_BACKUP=on needs the recipients file %s (the operators' and drill host's age recipients): %w", RecipientsFile, err)
	}
	if err := writeFileAtomic(filepath.Join(RunDir, "recipients.txt"), rec, 0o600); err != nil {
		return err
	}
	toml := fmt.Sprintf(`# Generated by sc-dc-init at every start (SC_BACKUP=on).
[backup]
enabled = true
peer_user = "conductor-backup"
account = %s
password_file = %s
server = "127.0.0.1"
dc = %s
recipients_file = %s
state_dir = "/var/lib/conductor-backup"
work_dir = "/tmp/conductor-backup"
conductor_db = "/var/lib/conductor/conductor.db"
`, strconv.Quote(c.BackupAccount), strconv.Quote(filepath.Join(RunDir, "backup-account")), strconv.Quote(c.Hostname),
		strconv.Quote(filepath.Join(RunDir, "recipients.txt")))
	return writeFileAtomic(p, []byte(toml), 0o600)
}
